---
title: "snRNA-seq analysis progress - 2; Tabeta et al."
author: "JS KIM"
date: "2024-12-12"
output: html_document
---

```{r setup, include=FALSE}
library(rgl) #for 3D-view incorporation
knitr::knit_hooks$set(webgl = hook_webgl) ##for 3D-view incorporation
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## Overview
Progress to analyze the single nucleus RNA-seq (snRNA-seq) of Arabidopsis 8-d-old cotyledons of two genotypes, wild-type and fugu5.
Start from the previous output "Tabeta-fugu5.seurat.rds".

```{r pkgs}
### Libraries
library(Seurat) #v4.4
library(phateR)

library(ggplot2)
library(pheatmap)

### Some usuful presets
ggcolor <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
`%notin%` <- Negate(`%in%`)

setwd("~/Library/CloudStorage/Box-Box/シングルセル解析(多部田)")
set.seed(101) #prevent the random output
```

## Load the Seurat dataset
Here to load the seurat dataset from merging two COPILOT sets.
```{r call db}
tbt1 <- readRDS("Tabeta-fugu5.seurat.rds")
tbt1 ##output the summary of db
```

## Data Transformation
```{r pca-umap-tsne}
##1. Collect the most variable genes
AllFeatures <- rownames(tbt1@assays$RNA@data)
tbt1 <- FindVariableFeatures(tbt1)
VariableFeaturePlot(tbt1, selection.method="vst")
VariableFeatures <- VariableFeatures(tbt1)

##2. PCA with the 2k variable genes
tbt1 <- ScaleData(tbt1, do.scale = TRUE, do.center = TRUE, features = AllFeatures, vars.to.regress = c("percent.mt","percent.cp"))
tbt1 <- RunPCA(tbt1, vervose=FALSE, approx=FALSE, npcs=50, features=VariableFeatures)
tbt1@reductions$pca_vst2k <- tbt1@reductions$pca #save the feature
ElbowPlot(tbt1, ndims=50, reduction="pca_vst2k")

##3. UMAP with the whole PCs
tbt1@reductions$pca <- tbt1@reductions$pca_vst2k #for assure
tbt1 <- RunUMAP(tbt1, reduction.key = "UMAP_", dims=c(1:50))
tbt1@reductions$umap_vst2k <- tbt1@reductions$umap
DimPlot(tbt1, reduction="umap_vst2k", group.by="orig.ident") + ggtitle("UMAP(vst2k)") + NoLegend()
tbt1 <- RunUMAP(tbt1, reduction.key = "UMAP_", dims=c(1:50), n.components=3)
tbt1@reductions$umap_3d <- tbt1@reductions$umap

##4. TSNE with the whole PCs
tbt1 <- RunTSNE(tbt1, reduction.key = "TSNE_", dims=c(1:50))
tbt1@reductions$tsne@cell.embeddings[,2] <- tbt1@reductions$tsne@cell.embeddings[,2]*-1 #reverse TSNE_2 for an aesthetic reason
tbt1@reductions$tsne_vst2k <- tbt1@reductions$tsne
DimPlot(tbt1, reduction="tsne_vst2k", group.by="orig.ident") + ggtitle("TSNE(vst2k)") 
tbt1 <- RunTSNE(tbt1, reduction.key = "TSNE_", dims=c(1:50), dim.embed=3)
tbt1@reductions$tsne_3d <- tbt1@reductions$tsne
```

## Clustering
```{r Clustering}
tbt1 = FindNeighbors(tbt1, dims=c(1:50)) 
tbt1 = FindClusters(tbt1,resolution = 0.5) #12
#tbt1$SCT_snn_res.0.5
tbt1 = FindClusters(tbt1,resolution = 1.0) #18
#tbt1$SCT_snn_res.1
tbt1 = FindClusters(tbt1,resolution = 1.5) #20
#tbt1$SCT_snn_res.1.5
tbt1 = FindClusters(tbt1,resolution = 2.0) #24
#tbt1$SCT_snn_res.2
tbt1 = FindClusters(tbt1,resolution = 3.0) #34
#tbt1$SCT_snn_res.3
tbt1 = FindClusters(tbt1,resolution = 4.0) #39
#tbt1$SCT_snn_res.4
tbt1 = FindClusters(tbt1,resolution = 5.0) #46
#tbt1$SCT_snn_res.5
tbt1$seurat_clusters <- tbt1$SCT_snn_res.5

P2 <- DimPlot(tbt1, reduction="tsne_vst2k", group.by="seurat_clusters", label=TRUE) + NoLegend() + ggtitle("TSNE(vst2k)") 
P1 <- DimPlot(tbt1, reduction="umap_vst2k", group.by="seurat_clusters", label=TRUE) + NoLegend() + ggtitle("UMAP(vst2k)") 
P1 + P2
```

## 3-D view I
```{r 3d1, webgl=TRUE}
meta <- tbt1@meta.data
levels(meta$seurat_clusters) <- seq(1,length(levels(meta$seurat_clusters))) #cluster 0->37 to color 1->38
plot3d(tbt1@reductions$umap_3d@cell.embeddings, xlab="UMAP_1", ylab="UMAP_2", zlab="UMAP_3", col=ggcolor(length(levels(meta$seurat_clusters)))[meta$seurat_clusters])
```

## 3-D view II
```{r 3d2, webgl=TRUE}
plot3d(tbt1@reductions$tsne_3d@cell.embeddings, xlab="TSNE_1", ylab="TSNE_2", zlab="TSNE_3", col=ggcolor(length(levels(meta$seurat_clusters)))[meta$seurat_clusters])
```

## Save the progress
```{r save the progress}
saveRDS(tbt1, "Tabeta-fugu5.seurat.v2.rds")
sessionInfo()
```

